name: Laravel CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CD
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install sshpass

    - name: Write password to file
      env:
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: echo $SERVER_PASSWORD > password.txt
      
    - name: Debugging
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo "SERVER_USER: $SERVER_USER"
        echo "SERVER_IP: $SERVER_IP"
        
    - name: Deploy to server
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        sshpass -f password.txt ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /var/www/html && git pull && composer install --no-dev && php artisan migrate --force"
